# Generated by Django 3.1 on 2020-08-26 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(blank=True, choices=[('one', '1'), ('two', '2'), ('three', '3'), ('four', '4')], default='', max_length=128),
        ),
    ]
