# Generated by Django 3.1 on 2020-08-28 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_tag_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='items',
        ),
        migrations.AddField(
            model_name='video',
            name='tags',
            field=models.ManyToManyField(related_name='taggedvideos', to='courses.Video'),
        ),
    ]
